"""empty message

Revision ID: c95094e7e113
Revises: f1de964d4c41
Create Date: 2026-02-15 00:03:13.815241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95094e7e113'
down_revision = 'f1de964d4c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_type_preset', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('body_type_proportions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('body_type_proportions')
        batch_op.drop_column('body_type_preset')

    # ### end Alembic commands ###
