"""empty message

Revision ID: f1de964d4c41
Revises: a972a8ee4002
Create Date: 2026-02-14 23:41:49.121642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1de964d4c41'
down_revision = 'a972a8ee4002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppet_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('head_image_url', sa.String(length=512), nullable=True),
    sa.Column('torso_image_url', sa.String(length=512), nullable=True),
    sa.Column('upper_arm_image_url', sa.String(length=512), nullable=True),
    sa.Column('lower_arm_image_url', sa.String(length=512), nullable=True),
    sa.Column('upper_leg_image_url', sa.String(length=512), nullable=True),
    sa.Column('lower_leg_image_url', sa.String(length=512), nullable=True),
    sa.Column('hand_image_url', sa.String(length=512), nullable=True),
    sa.Column('foot_image_url', sa.String(length=512), nullable=True),
    sa.Column('pivot_config', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mocap_session_2d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puppet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('pose_data_url', sa.String(length=512), nullable=True),
    sa.Column('face_data_url', sa.String(length=512), nullable=True),
    sa.Column('combined_data_url', sa.String(length=512), nullable=True),
    sa.Column('export_format', sa.String(length=20), nullable=True),
    sa.Column('exported_file_url', sa.String(length=512), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('beat_timestamps', sa.JSON(), nullable=True),
    sa.Column('has_face_tracking', sa.Boolean(), nullable=True),
    sa.Column('has_body_tracking', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puppet_id'], ['puppet_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illustration_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('original_image_url', sa.String(length=512), nullable=False),
    sa.Column('illustration_type', sa.String(length=20), nullable=False),
    sa.Column('depth_map_url', sa.String(length=512), nullable=True),
    sa.Column('model_url', sa.String(length=512), nullable=True),
    sa.Column('export_format', sa.String(length=10), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('has_back_face', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('is_rigged', sa.Boolean(), nullable=True),
    sa.Column('rigged_avatar_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ),
    sa.ForeignKeyConstraint(['rigged_avatar_id'], ['rigged_avatar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mocap_2d_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('illustration_conversions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.drop_column('illustration_conversions')
        batch_op.drop_column('mocap_2d_sessions')

    op.drop_table('illustration_conversion')
    op.drop_table('mocap_session_2d')
    op.drop_table('puppet_character')
    # ### end Alembic commands ###
